# Generated by Django 5.0.1 on 2024-01-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='content',
            new_name='contents',
        ),
    ]
